version: '1'
services:
  db:
    image: postgres:latest
    container_name: Database
    environment:
      POSTGRES_DB: StarStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: StarStore.API
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE: Host=db;Database=StarStore;Username=postgres;Password=senha